name: AutoCheck

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v1
      - name: Check New Commit
        run: |
          legadoUrl=https://github.com/gedoor/legado
          asters1Url=https://github.com/asters1/legado
          echo "legadoUrl=$legadoUrl" >> $GITHUB_ENV
          echo ${{ env.legadoUrl }}
