name: AutoCheck

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v1
      - name: Check New Commit
        run: |
          legadoUrl=https://github.com/gedoor/legado
          asters1Url=https://github.com/asters1/legado
          echo "legadoUrl=$legadoUrl" >> $GITHUB_ENV
          echo "asters1Url=$asters1Url" >> $GITHUB_ENV

          legadoCommit=$(curl -sL $legadoUrl/commits/master |grep -o "/gedoor/legado/commit/[a-z0-9]\+" |head -1 | cut -d\/ -f5)
          asters1Commit=$(curl -sL $asters1Url/commits/master |grep -o "/asters1/legado/commit/[a-z0-9]\+" |head -1 | cut -d\/ -f5)
          if [ ! $legadoCommit == $asters1Commit ];then
          
          echo "不等"
          echo "legadoCommit=$legadoCommit" >> $GITHUB_ENV
          echo "asters1Commit=$asters1Commit" >> $GITHUB_ENV
          fi
      - name: Clone and Push
        if: ${{ env.legadoCommit }}
        run: |
          git clone ${{env.legadoUrl}} cs
          echo ${{env.asters1Commit}}
          echo ${{env.legadoCommit}}
          cd cs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote rm origin
          git remote add origin "https://${{ secrets.USER }}:${{ secrets.USER_TOKEN }}@github.com/asters1/legado"
          git push -f -u origin master


     
