name: CheckTvjar

on:
  push:
    branches: 
      - master
    paths:
      - 'tvjar/tvjarCommit.json'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check New Commit
        run: |
          chmod +x ./jq
          oldcommit=$(./jq ./tvjar/tvjarCommit.json old)
          newcommit=$(./jq ./tvjar/tvjarCommit.json new)
          echo "oldcommit=$oldcommit">> $GITHUB_ENV
          echo "newcommit=$newcommit">> $GITHUB_ENV
      - name: Check file
        run: |
          git clone https://asters1:${{secrets.USER_TOKEN}}@github.com/asters1/tvjar_test
          cd tvjar_test
          Info=$(git diff ${{ env.oldcommit }} ${{ env.newcommit }} --stat)
          Change_file_path=${Info% |*}
          if [ ${#Change_file_path} -gt 42  ];then
          echo ${Change_file_path:0:44} 
          echo "app/src/main/java/com/github/catvod/spider/"
            if [ ${Change_file_path:0:44} == "app/src/main/java/com/github/catvod/spider/" ];then
            echo "Change_file_path=${Change_file_path# }" >> $GITHUB_ENV
            echo "Change_file_name=${Change_file_path##*/}" >> $GITHUB_ENV

            fi
          fi
      - name: Clone tvjar
        if: ${{ env.Change_file_path }}
        run: |
          git clone https://asters1:${{ secrets.USER_TOKEN }}@github.com/asters1/tvjar tvjar1
          cd tvjar1
          rm -rf ${{ env.Change_file_path}}
          cp ../tvjar_test/${{ env.Change_file_path }} ${{ env.Change_file_path }}
          sed -i '/extends Spider/a}' ${{ env.Change_file_path }}
          sed -i '/extends Spider/asuper.init(context);' ${{ env.Change_file_path }}
          sed -i '/extends Spider/apublic void init(Context context) {' ${{ env.Change_file_path }}
          sed -i '/extends Spider/a@Override' -i ${{ env.Change_file_path }}
          sed -i '/package com.github.catvod.spider;/aimport android.content.Context;' ${{ env.Change_file_path }}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "${{ env.Change_file_name }}"
          git push -u -f origin master


