name: CheckTvjar

on:
  push:
    branches: 
      - master
        #  paths:
        #    - 'tvjar/tvjarCommit.json'
    pull_request:
      workflow_dispatch:

        jobs:
          build:
            runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check New Commit
        run: |
          chmod +x ./jq
          oldcommit=$(./jq ./tvjar/tvjarCommit.json old)
          newcommit=$(./jq ./tvjar/tvjarCommit.json new)
          echo "oldcommit=$oldcommit">> $GITHUB_ENV
          echo "newcommit=$newcommit">> $GITHUB_ENV
      - name: Change Java
        run: |
          echo ${{ env.oldcommit }}
          echo ${{ env.newcommit }}
          Change_file_path=$(git diff ${{ oldcommit }} ${{ env.newcommit }} --stat)
          echo $Change_file_path

